// api/src/domain/types.ts

export enum FlightType {
  INBOUND = "INBOUND",
  OUTBOUND = "OUTBOUND",
}

export enum EmergencyStatus {
  NONE = "NONE",
  FUEL = "FUEL",
  MECHANICAL_FAILURE = "MECHANICAL_FAILURE",
  PASSENGER_HEALTH = "PASSENGER_HEALTH",
}

export enum AircraftState {
  ENTERING_SIM = "ENTERING_SIM",
  HOLDING = "HOLDING",
  TAKEOFF_QUEUE = "TAKEOFF_QUEUE",
  RUNWAY = "RUNWAY",
  EXITED = "EXITED",
  CANCELLED = "CANCELLED",
  DIVERTED = "DIVERTED",
}

export enum RunwayMode {
  LANDING = "LANDING",
  TAKEOFF = "TAKEOFF",
  MIXED = "MIXED",
}

export enum RunwayStatus {
  AVAILABLE = "AVAILABLE",
  OCCUPIED = "OCCUPIED",
  RUNWAY_INSPECTION = "RUNWAY_INSPECTION",
  SNOW_CLEARANCE = "SNOW_CLEARANCE",
  EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE",
}